apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: client-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: emartapp-main-client
          ports:
            - containerPort: 4200
          env:
            - name: API_URL
              value: http://api-service:5000
            - name: WEB_API_URL
              value: http://webapi-service:9000

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: emartapp-main-api
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_DB_URL
              value: mongodb://emongo-service:27017/epoc

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapi-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi
          image: emartapp-main-webapi
          ports:
            - containerPort: 9000
          env:
            - name: MYSQL_DB_HOST
              value: emartdb-service:3306
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: emongo-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emongo
  template:
    metadata:
      labels:
        app: emongo
    spec:
      containers:
        - name: emongo
          image: mongo:4
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: epoc

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: emartdb-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emartdb
  template:
    metadata:
      labels:
        app: emartdb
    spec:
      containers:
        - name: emartdb
          image: mysql:8.0.33
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: emartdbpass
            - name: MYSQL_DATABASE
              value: books